### ISSUE TITLE
What is genCSR?

### ISSUE THREAD

**Issue by nizhegorodets** [tudelft-atlarge/graphalytics-platforms-openg#18]
I'm trying start benchmark for Openg but I caught 

`../openg/graphalytics-1.0.0-openg-0.2-SNAPSHOT/bin/sh/../../bin/exe/genCSR: No such file or directory
`
I found this in load-graph.sh

COMMAND="$rootdir/bin/exe/genCSR \

**Comment by AhmedMusaafir** [comment]
Hi,

Assuming that you have compiled OpenG, have you also compiled the benchmark by running `bin/sh/compile-benchmark.sh`?

**Comment by nizhegorodets** [comment]
Thank you so much! 
I really forgot about it

But I have a new error: 

> ./bin/sh/compile-benchmark.sh 
-- The CXX compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
CMake Error at CMakeLists.txt:39 (add_executable):
  Cannot find source file:

>  /home/dmitry/Desktop/ldbc/openg/graphBIG/graphalytics/tool_convert/main.cpp

>   Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
CMake Error: CMake can not determine linker language for target: genCSR
CMake Error: Cannot determine link language for target "genCSR".

I can't find a folder **tool_convert** anywhere

**Comment by amusaafir** [comment]
Did you compile OpenG from the [Graphalytics branch](https://github.com/graphbig/graphBIG/tree/graphalytics)?

**Comment by AhmedMusaafir** [comment]
Did you compile OpenG from the [Graphalytics branch](https://github.com/graphbig/graphBIG/tree/graphalytics)?

**Comment by nizhegorodets** [comment]
Yes, it was necessary to switch to this branch. Benchmark successfully launched!
Thank!
