### ISSUE TITLE
mvn install puts the .jar file in the /lib instead of /target.

### ISSUE THREAD

**Issue by sampollard** [tudelft-atlarge/graphalytics-platforms-openg#6]
The package-benchmark.sh script from Graphalytics expects the following directory:
/specified-directory/graphalytics-platforms-openg/graphalytics-0.3-openg-0.1/target/graphalytics-platforms-openg-0.1.jar

while the mvn package would generate
/specified-directory/graphalytics-platforms-openg/graphalytics-0.3-openg-0.1/**lib**/graphalytics-platforms-openg-**std**-0.1.jar

Is there something I'm missing here?

**Comment by thegeman** [comment]
We stopped using the package-benchmark script in favor of a simplified build process using maven, but forgot to delete the script. Sorry for the inconvenience.

Please refer to the "how to build" section of the main Graphalytics repository for the updated process: https://github.com/ldbc/ldbc_graphalytics#how-to-build-graphalytics
